[
  {
    "courseCode": "course_001",
    "title": "React Native Masterclass",
    "subtitle": "Become proficient in React Native Masterclass",
    "description": "Comprehensive hands-on course covering React Native Masterclass with projects and best practices.",
    "thumbnail": "/assets/images/thumbnail/course_001_thumbnail.png",
    "bannerImage": "/assets/images/banner/course_001_banner.png",
    "instructor": "Emma Watson",
    "category": "Mobile Development",
    "level": "Intermediate",
    "language": "English",
    "duration": "10h 51m",
    "totalLessons": 76,
    "rating": 4.3,
    "totalStudents": 15020,
    "price": 2999,
    "discountPrice": 2299,
    "isFeatured": true,
    "isPopular": false,
    "tags": [
      "React Native",
      "Android",
      "iOS",
      "Mobile"
    ],
    "createdAt": "2026-07-01T10:00:00.000Z",
    "updatedAt": "2026-07-20T12:00:00.000Z"
  },
  {
    "courseCode": "course_002",
    "title": "React Native New Architecture",
    "subtitle": "Become proficient in React Native New Architecture",
    "description": "Comprehensive hands-on course covering React Native New Architecture with projects and best practices.",
    "thumbnail": "/assets/images/thumbnail/course_002_thumbnail.png",
    "bannerImage": "/assets/images/banner/course_002_banner.png",
    "instructor": "Emma Watson",
    "category": "Mobile Development",
    "level": "Beginner",
    "language": "English",
    "duration": "19h 43m",
    "totalLessons": 65,
    "rating": 4.9,
    "totalStudents": 1524,
    "price": 1499,
    "discountPrice": 499,
    "isFeatured": true,
    "isPopular": false,
    "tags": [
      "React Native",
      "Android",
      "iOS",
      "Mobile"
    ],
    "createdAt": "2026-07-01T10:00:00.000Z",
    "updatedAt": "2026-07-20T12:00:00.000Z"
  },
  {
    "courseCode": "course_003",
    "title": "Redux Toolkit Complete Guide",
    "subtitle": "Become proficient in Redux Toolkit Complete Guide",
    "description": "Comprehensive hands-on course covering Redux Toolkit Complete Guide with projects and best practices.",
    "thumbnail": "/assets/images/thumbnail/course_003_thumbnail.png",
    "bannerImage": "/assets/images/banner/course_003_banner.png",
    "instructor": "John Smith",
    "category": "Mobile Development",
    "level": "Beginner",
    "language": "English",
    "duration": "23h 28m",
    "totalLessons": 43,
    "rating": 4.7,
    "totalStudents": 20983,
    "price": 2999,
    "discountPrice": 1999,
    "isFeatured": true,
    "isPopular": true,
    "tags": [
      "React Native",
      "Android",
      "iOS",
      "Mobile"
    ],
    "createdAt": "2026-07-01T10:00:00.000Z",
    "updatedAt": "2026-07-20T12:00:00.000Z"
  },
  {
    "courseCode": "course_004",
    "title": "Node.js & Express API Development",
    "subtitle": "Become proficient in Node.js & Express API Development",
    "description": "Comprehensive hands-on course covering Node.js & Express API Development with projects and best practices.",
    "thumbnail": "/assets/images/thumbnail/course_004_thumbnail.png",
    "bannerImage": "/assets/images/banner/course_004_banner.png",
    "instructor": "Emma Watson",
    "category": "Backend Development",
    "level": "Advanced",
    "language": "English",
    "duration": "13h 12m",
    "totalLessons": 41,
    "rating": 4.7,
    "totalStudents": 38409,
    "price": 1499,
    "discountPrice": 1199,
    "isFeatured": true,
    "isPopular": false,
    "tags": [
      "Node.js",
      "Express",
      "API"
    ],
    "createdAt": "2026-07-01T10:00:00.000Z",
    "updatedAt": "2026-07-20T12:00:00.000Z"
  },
  {
    "courseCode": "course_005",
    "title": "MongoDB From Scratch",
    "subtitle": "Become proficient in MongoDB From Scratch",
    "description": "Comprehensive hands-on course covering MongoDB From Scratch with projects and best practices.",
    "thumbnail": "/assets/images/thumbnail/course_005_thumbnail.png",
    "bannerImage": "/assets/images/banner/course_005_banner.png",
    "instructor": "Emma Watson",
    "category": "Database",
    "level": "Beginner",
    "language": "English",
    "duration": "17h 2m",
    "totalLessons": 56,
    "rating": 4.5,
    "totalStudents": 7861,
    "price": 1999,
    "discountPrice": 1299,
    "isFeatured": true,
    "isPopular": false,
    "tags": [
      "MongoDB",
      "NoSQL"
    ],
    "createdAt": "2026-07-01T10:00:00.000Z",
    "updatedAt": "2026-07-20T12:00:00.000Z"
  },
  {
    "courseCode": "course_006",
    "title": "Modern JavaScript",
    "subtitle": "Become proficient in Modern JavaScript",
    "description": "Comprehensive hands-on course covering Modern JavaScript with projects and best practices.",
    "thumbnail": "/assets/images/thumbnail/course_006_thumbnail.png",
    "bannerImage": "/assets/images/banner/course_006_banner.png",
    "instructor": "Olivia Wilson",
    "category": "Frontend Development",
    "level": "Advanced",
    "language": "English",
    "duration": "24h 29m",
    "totalLessons": 28,
    "rating": 4.6,
    "totalStudents": 27575,
    "price": 1499,
    "discountPrice": 1199,
    "isFeatured": false,
    "isPopular": true,
    "tags": [
      "React",
      "JavaScript",
      "TypeScript"
    ],
    "createdAt": "2026-07-01T10:00:00.000Z",
    "updatedAt": "2026-07-20T12:00:00.000Z"
  },
  {
    "courseCode": "course_007",
    "title": "TypeScript Bootcamp",
    "subtitle": "Become proficient in TypeScript Bootcamp",
    "description": "Comprehensive hands-on course covering TypeScript Bootcamp with projects and best practices.",
    "thumbnail": "/assets/images/thumbnail/course_007_thumbnail.png",
    "bannerImage": "/assets/images/banner/course_007_banner.png",
    "instructor": "Olivia Wilson",
    "category": "Frontend Development",
    "level": "Advanced",
    "language": "English",
    "duration": "10h 30m",
    "totalLessons": 57,
    "rating": 4.9,
    "totalStudents": 6101,
    "price": 2499,
    "discountPrice": 1999,
    "isFeatured": false,
    "isPopular": false,
    "tags": [
      "React",
      "JavaScript",
      "TypeScript"
    ],
    "createdAt": "2026-07-01T10:00:00.000Z",
    "updatedAt": "2026-07-20T12:00:00.000Z"
  },
  {
    "courseCode": "course_008",
    "title": "React.js Complete Course",
    "subtitle": "Become proficient in React.js Complete Course",
    "description": "Comprehensive hands-on course covering React.js Complete Course with projects and best practices.",
    "thumbnail": "/assets/images/thumbnail/course_008_thumbnail.png",
    "bannerImage": "/assets/images/banner/course_008_banner.png",
    "instructor": "Chris Evans",
    "category": "Frontend Development",
    "level": "Beginner",
    "language": "English",
    "duration": "12h 57m",
    "totalLessons": 78,
    "rating": 4.8,
    "totalStudents": 7440,
    "price": 2999,
    "discountPrice": 2699,
    "isFeatured": false,
    "isPopular": false,
    "tags": [
      "React",
      "JavaScript",
      "TypeScript"
    ],
    "createdAt": "2026-07-01T10:00:00.000Z",
    "updatedAt": "2026-07-20T12:00:00.000Z"
  },
  {
    "courseCode": "course_009",
    "title": "Kotlin for Android",
    "subtitle": "Become proficient in Kotlin for Android",
    "description": "Comprehensive hands-on course covering Kotlin for Android with projects and best practices.",
    "thumbnail": "/assets/images/thumbnail/course_009_thumbnail.png",
    "bannerImage": "/assets/images/banner/course_009_banner.png",
    "instructor": "Emma Watson",
    "category": "Android",
    "level": "Intermediate",
    "language": "English",
    "duration": "6h 21m",
    "totalLessons": 48,
    "rating": 4.5,
    "totalStudents": 24395,
    "price": 999,
    "discountPrice": 499,
    "isFeatured": false,
    "isPopular": true,
    "tags": [
      "Android",
      "Kotlin",
      "Jetpack Compose"
    ],
    "createdAt": "2026-07-01T10:00:00.000Z",
    "updatedAt": "2026-07-20T12:00:00.000Z"
  },
  {
    "courseCode": "course_010",
    "title": "SwiftUI Essentials",
    "subtitle": "Become proficient in SwiftUI Essentials",
    "description": "Comprehensive hands-on course covering SwiftUI Essentials with projects and best practices.",
    "thumbnail": "/assets/images/thumbnail/course_010_thumbnail.png",
    "bannerImage": "/assets/images/banner/course_010_banner.png",
    "instructor": "David Warner",
    "category": "iOS",
    "level": "Beginner",
    "language": "English",
    "duration": "21h 13m",
    "totalLessons": 25,
    "rating": 4.4,
    "totalStudents": 23565,
    "price": 1499,
    "discountPrice": 499,
    "isFeatured": false,
    "isPopular": false,
    "tags": [
      "SwiftUI",
      "iOS"
    ],
    "createdAt": "2026-07-01T10:00:00.000Z",
    "updatedAt": "2026-07-20T12:00:00.000Z"
  },
  {
    "courseCode": "course_011",
    "title": "Android Jetpack Compose",
    "subtitle": "Become proficient in Android Jetpack Compose",
    "description": "Comprehensive hands-on course covering Android Jetpack Compose with projects and best practices.",
    "thumbnail": "/assets/images/thumbnail/course_011_thumbnail.png",
    "bannerImage": "/assets/images/banner/course_011_banner.png",
    "instructor": "David Warner",
    "category": "Android",
    "level": "Beginner",
    "language": "English",
    "duration": "26h 26m",
    "totalLessons": 23,
    "rating": 4.8,
    "totalStudents": 31659,
    "price": 1999,
    "discountPrice": 1699,
    "isFeatured": false,
    "isPopular": false,
    "tags": [
      "Android",
      "Kotlin",
      "Jetpack Compose"
    ],
    "createdAt": "2026-07-01T10:00:00.000Z",
    "updatedAt": "2026-07-20T12:00:00.000Z"
  },
  {
    "courseCode": "course_012",
    "title": "Firebase for Mobile Apps",
    "subtitle": "Become proficient in Firebase for Mobile Apps",
    "description": "Comprehensive hands-on course covering Firebase for Mobile Apps with projects and best practices.",
    "thumbnail": "/assets/images/thumbnail/course_012_thumbnail.png",
    "bannerImage": "/assets/images/banner/course_012_banner.png",
    "instructor": "Michael Scott",
    "category": "Backend Development",
    "level": "Advanced",
    "language": "English",
    "duration": "24h 14m",
    "totalLessons": 62,
    "rating": 4.5,
    "totalStudents": 10337,
    "price": 999,
    "discountPrice": 499,
    "isFeatured": false,
    "isPopular": true,
    "tags": [
      "Node.js",
      "Express",
      "API"
    ],
    "createdAt": "2026-07-01T10:00:00.000Z",
    "updatedAt": "2026-07-20T12:00:00.000Z"
  },
  {
    "courseCode": "course_013",
    "title": "Git & GitHub Masterclass",
    "subtitle": "Become proficient in Git & GitHub Masterclass",
    "description": "Comprehensive hands-on course covering Git & GitHub Masterclass with projects and best practices.",
    "thumbnail": "/assets/images/thumbnail/course_013_thumbnail.png",
    "bannerImage": "/assets/images/banner/course_013_banner.png",
    "instructor": "Emma Watson",
    "category": "Tools",
    "level": "Advanced",
    "language": "English",
    "duration": "9h 0m",
    "totalLessons": 60,
    "rating": 4.2,
    "totalStudents": 38575,
    "price": 2499,
    "discountPrice": 1799,
    "isFeatured": false,
    "isPopular": false,
    "tags": [
      "Git",
      "GitHub"
    ],
    "createdAt": "2026-07-01T10:00:00.000Z",
    "updatedAt": "2026-07-20T12:00:00.000Z"
  },
  {
    "courseCode": "course_014",
    "title": "REST API Design",
    "subtitle": "Become proficient in REST API Design",
    "description": "Comprehensive hands-on course covering REST API Design with projects and best practices.",
    "thumbnail": "/assets/images/thumbnail/course_014_thumbnail.png",
    "bannerImage": "/assets/images/banner/course_014_banner.png",
    "instructor": "Emma Watson",
    "category": "Backend Development",
    "level": "Intermediate",
    "language": "English",
    "duration": "8h 38m",
    "totalLessons": 42,
    "rating": 4.7,
    "totalStudents": 8791,
    "price": 1999,
    "discountPrice": 1499,
    "isFeatured": false,
    "isPopular": false,
    "tags": [
      "Node.js",
      "Express",
      "API"
    ],
    "createdAt": "2026-07-01T10:00:00.000Z",
    "updatedAt": "2026-07-20T12:00:00.000Z"
  },
  {
    "courseCode": "course_015",
    "title": "Docker Fundamentals",
    "subtitle": "Become proficient in Docker Fundamentals",
    "description": "Comprehensive hands-on course covering Docker Fundamentals with projects and best practices.",
    "thumbnail": "/assets/images/thumbnail/course_015_thumbnail.png",
    "bannerImage": "/assets/images/banner/course_015_banner.png",
    "instructor": "Alex Johnson",
    "category": "DevOps",
    "level": "Intermediate",
    "language": "English",
    "duration": "28h 47m",
    "totalLessons": 32,
    "rating": 4.3,
    "totalStudents": 31777,
    "price": 2499,
    "discountPrice": 1499,
    "isFeatured": false,
    "isPopular": true,
    "tags": [
      "Docker",
      "CI/CD"
    ],
    "createdAt": "2026-07-01T10:00:00.000Z",
    "updatedAt": "2026-07-20T12:00:00.000Z"
  },
  {
    "courseCode": "course_016",
    "title": "UI Design with Figma",
    "subtitle": "Become proficient in UI Design with Figma",
    "description": "Comprehensive hands-on course covering UI Design with Figma with projects and best practices.",
    "thumbnail": "/assets/images/thumbnail/course_016_thumbnail.png",
    "bannerImage": "/assets/images/banner/course_016_banner.png",
    "instructor": "Robert King",
    "category": "UI/UX",
    "level": "Intermediate",
    "language": "English",
    "duration": "9h 55m",
    "totalLessons": 71,
    "rating": 4.5,
    "totalStudents": 45864,
    "price": 2499,
    "discountPrice": 1499,
    "isFeatured": false,
    "isPopular": false,
    "tags": [
      "Figma",
      "Design"
    ],
    "createdAt": "2026-07-01T10:00:00.000Z",
    "updatedAt": "2026-07-20T12:00:00.000Z"
  },
  {
    "courseCode": "course_017",
    "title": "AI for Developers",
    "subtitle": "Become proficient in AI for Developers",
    "description": "Comprehensive hands-on course covering AI for Developers with projects and best practices.",
    "thumbnail": "/assets/images/thumbnail/course_017_thumbnail.png",
    "bannerImage": "/assets/images/banner/course_017_banner.png",
    "instructor": "Olivia Wilson",
    "category": "AI",
    "level": "Beginner",
    "language": "English",
    "duration": "22h 59m",
    "totalLessons": 73,
    "rating": 5,
    "totalStudents": 14621,
    "price": 2999,
    "discountPrice": 2499,
    "isFeatured": false,
    "isPopular": false,
    "tags": [
      "AI",
      "ML"
    ],
    "createdAt": "2026-07-01T10:00:00.000Z",
    "updatedAt": "2026-07-20T12:00:00.000Z"
  },
  {
    "courseCode": "course_018",
    "title": "Machine Learning Basics",
    "subtitle": "Become proficient in Machine Learning Basics",
    "description": "Comprehensive hands-on course covering Machine Learning Basics with projects and best practices.",
    "thumbnail": "/assets/images/thumbnail/course_018_thumbnail.png",
    "bannerImage": "/assets/images/banner/course_018_banner.png",
    "instructor": "Chris Evans",
    "category": "AI",
    "level": "Beginner",
    "language": "English",
    "duration": "6h 56m",
    "totalLessons": 25,
    "rating": 4.4,
    "totalStudents": 37769,
    "price": 1499,
    "discountPrice": 799,
    "isFeatured": false,
    "isPopular": true,
    "tags": [
      "AI",
      "ML"
    ],
    "createdAt": "2026-07-01T10:00:00.000Z",
    "updatedAt": "2026-07-20T12:00:00.000Z"
  },
  {
    "courseCode": "course_019",
    "title": "Python Fundamentals",
    "subtitle": "Become proficient in Python Fundamentals",
    "description": "Comprehensive hands-on course covering Python Fundamentals with projects and best practices.",
    "thumbnail": "/assets/images/thumbnail/course_019_thumbnail.png",
    "bannerImage": "/assets/images/banner/course_019_banner.png",
    "instructor": "David Warner",
    "category": "Programming",
    "level": "Intermediate",
    "language": "English",
    "duration": "29h 35m",
    "totalLessons": 75,
    "rating": 4.9,
    "totalStudents": 47583,
    "price": 1999,
    "discountPrice": 999,
    "isFeatured": false,
    "isPopular": false,
    "tags": [
      "Python"
    ],
    "createdAt": "2026-07-01T10:00:00.000Z",
    "updatedAt": "2026-07-20T12:00:00.000Z"
  },
  {
    "courseCode": "course_020",
    "title": "Clean Architecture",
    "subtitle": "Become proficient in Clean Architecture",
    "description": "Comprehensive hands-on course covering Clean Architecture with projects and best practices.",
    "thumbnail": "/assets/images/thumbnail/course_020_thumbnail.png",
    "bannerImage": "/assets/images/banner/course_020_banner.png",
    "instructor": "Emma Watson",
    "category": "Software Architecture",
    "level": "Advanced",
    "language": "English",
    "duration": "7h 38m",
    "totalLessons": 68,
    "rating": 4.7,
    "totalStudents": 44327,
    "price": 2499,
    "discountPrice": 1499,
    "isFeatured": false,
    "isPopular": false,
    "tags": [
      "Clean Architecture"
    ],
    "createdAt": "2026-07-01T10:00:00.000Z",
    "updatedAt": "2026-07-20T12:00:00.000Z"
  },
  {
    "courseCode": "course_021",
    "title": "GraphQL Essentials",
    "subtitle": "Become proficient in GraphQL Essentials",
    "description": "Comprehensive hands-on course covering GraphQL Essentials with projects and best practices.",
    "thumbnail": "/assets/images/thumbnail/course_021_thumbnail.png",
    "bannerImage": "/assets/images/banner/course_021_banner.png",
    "instructor": "Robert King",
    "category": "Backend Development",
    "level": "Intermediate",
    "language": "English",
    "duration": "19h 42m",
    "totalLessons": 72,
    "rating": 4.3,
    "totalStudents": 23226,
    "price": 2999,
    "discountPrice": 2499,
    "isFeatured": false,
    "isPopular": true,
    "tags": [
      "Node.js",
      "Express",
      "API"
    ],
    "createdAt": "2026-07-01T10:00:00.000Z",
    "updatedAt": "2026-07-20T12:00:00.000Z"
  },
  {
    "courseCode": "course_022",
    "title": "Next.js in Production",
    "subtitle": "Become proficient in Next.js in Production",
    "description": "Comprehensive hands-on course covering Next.js in Production with projects and best practices.",
    "thumbnail": "/assets/images/thumbnail/course_022_thumbnail.png",
    "bannerImage": "/assets/images/banner/course_022_banner.png",
    "instructor": "Michael Scott",
    "category": "Frontend Development",
    "level": "Beginner",
    "language": "English",
    "duration": "15h 3m",
    "totalLessons": 72,
    "rating": 5,
    "totalStudents": 28696,
    "price": 2999,
    "discountPrice": 2499,
    "isFeatured": false,
    "isPopular": false,
    "tags": [
      "React",
      "JavaScript",
      "TypeScript"
    ],
    "createdAt": "2026-07-01T10:00:00.000Z",
    "updatedAt": "2026-07-20T12:00:00.000Z"
  },
  {
    "courseCode": "course_023",
    "title": "AWS for Beginners",
    "subtitle": "Become proficient in AWS for Beginners",
    "description": "Comprehensive hands-on course covering AWS for Beginners with projects and best practices.",
    "thumbnail": "/assets/images/thumbnail/course_023_thumbnail.png",
    "bannerImage": "/assets/images/banner/course_023_banner.png",
    "instructor": "Sarah Brown",
    "category": "Cloud",
    "level": "Advanced",
    "language": "English",
    "duration": "12h 38m",
    "totalLessons": 46,
    "rating": 4.7,
    "totalStudents": 13550,
    "price": 1999,
    "discountPrice": 1299,
    "isFeatured": false,
    "isPopular": false,
    "tags": [
      "AWS"
    ],
    "createdAt": "2026-07-01T10:00:00.000Z",
    "updatedAt": "2026-07-20T12:00:00.000Z"
  },
  {
    "courseCode": "course_024",
    "title": "CI/CD with GitHub Actions",
    "subtitle": "Become proficient in CI/CD with GitHub Actions",
    "description": "Comprehensive hands-on course covering CI/CD with GitHub Actions with projects and best practices.",
    "thumbnail": "/assets/images/thumbnail/course_024_thumbnail.png",
    "bannerImage": "/assets/images/banner/course_024_banner.png",
    "instructor": "Chris Evans",
    "category": "DevOps",
    "level": "Intermediate",
    "language": "English",
    "duration": "20h 30m",
    "totalLessons": 45,
    "rating": 4.3,
    "totalStudents": 46239,
    "price": 1499,
    "discountPrice": 999,
    "isFeatured": false,
    "isPopular": true,
    "tags": [
      "Docker",
      "CI/CD"
    ],
    "createdAt": "2026-07-01T10:00:00.000Z",
    "updatedAt": "2026-07-20T12:00:00.000Z"
  },
  {
    "courseCode": "course_025",
    "title": "Testing React Native Apps",
    "subtitle": "Become proficient in Testing React Native Apps",
    "description": "Comprehensive hands-on course covering Testing React Native Apps with projects and best practices.",
    "thumbnail": "/assets/images/thumbnail/course_025_thumbnail.png",
    "bannerImage": "/assets/images/banner/course_025_banner.png",
    "instructor": "John Smith",
    "category": "Mobile Development",
    "level": "Beginner",
    "language": "English",
    "duration": "13h 53m",
    "totalLessons": 41,
    "rating": 4.8,
    "totalStudents": 21072,
    "price": 2999,
    "discountPrice": 2299,
    "isFeatured": false,
    "isPopular": false,
    "tags": [
      "React Native",
      "Android",
      "iOS",
      "Mobile"
    ],
    "createdAt": "2026-07-01T10:00:00.000Z",
    "updatedAt": "2026-07-20T12:00:00.000Z"
  }
]