const lessons = [
  {
    "courseCode": "course_001",
    "lessonCode": "lesson_001",
    "lessonNumber": 1,
    "title": "Welcome to React Native Masterclass",
    "description": "Course introduction, roadmap, and what you'll build by the end of \"React Native Masterclass\".",
    "thumbnail": "/assets/images/lesson/lesson_001_thumbnail.png",
    "videoUrl": "/videos/course_001/lesson_001.mp4",
    "duration": "08:14",
    "order": 1,
    "isPreview": true,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_001",
    "lessonCode": "lesson_002",
    "lessonNumber": 2,
    "title": "Setting Up Your React Native Environment",
    "description": "Install the required tools and set up your development environment for this course.",
    "thumbnail": "/assets/images/lesson/lesson_002_thumbnail.png",
    "videoUrl": "/videos/course_001/lesson_002.mp4",
    "duration": "19:02",
    "order": 2,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_001",
    "lessonCode": "lesson_003",
    "lessonNumber": 3,
    "title": "Set up and structure a scalable React Native project",
    "description": "Hands-on lesson covering: set up and structure a scalable React Native project.",
    "thumbnail": "/assets/images/lesson/lesson_003_thumbnail.png",
    "videoUrl": "/videos/course_001/lesson_003.mp4",
    "duration": "19:27",
    "order": 3,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_001",
    "lessonCode": "lesson_004",
    "lessonNumber": 4,
    "title": "Build responsive UIs that work across Android and iOS",
    "description": "Hands-on lesson covering: build responsive UIs that work across Android and iOS.",
    "thumbnail": "/assets/images/lesson/lesson_004_thumbnail.png",
    "videoUrl": "/videos/course_001/lesson_004.mp4",
    "duration": "16:33",
    "order": 4,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_001",
    "lessonCode": "lesson_005",
    "lessonNumber": 5,
    "title": "Implement navigation with React Navigation",
    "description": "Hands-on lesson covering: implement navigation with React Navigation.",
    "thumbnail": "/assets/images/lesson/lesson_005_thumbnail.png",
    "videoUrl": "/videos/course_001/lesson_005.mp4",
    "duration": "18:25",
    "order": 5,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_001",
    "lessonCode": "lesson_006",
    "lessonNumber": 6,
    "title": "Connect native modules and third-party libraries",
    "description": "Hands-on lesson covering: connect native modules and third-party libraries.",
    "thumbnail": "/assets/images/lesson/lesson_006_thumbnail.png",
    "videoUrl": "/videos/course_001/lesson_006.mp4",
    "duration": "26:23",
    "order": 6,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_001",
    "lessonCode": "lesson_007",
    "lessonNumber": 7,
    "title": "Optimize app performance and debug effectively",
    "description": "Hands-on lesson covering: optimize app performance and debug effectively.",
    "thumbnail": "/assets/images/lesson/lesson_007_thumbnail.png",
    "videoUrl": "/videos/course_001/lesson_007.mp4",
    "duration": "17:55",
    "order": 7,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_002",
    "lessonCode": "lesson_008",
    "lessonNumber": 1,
    "title": "Welcome to React Native New Architecture",
    "description": "Course introduction, roadmap, and what you'll build by the end of \"React Native New Architecture\".",
    "thumbnail": "/assets/images/lesson/lesson_008_thumbnail.png",
    "videoUrl": "/videos/course_002/lesson_008.mp4",
    "duration": "06:38",
    "order": 1,
    "isPreview": true,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_002",
    "lessonCode": "lesson_009",
    "lessonNumber": 2,
    "title": "Setting Up Your React Native Environment",
    "description": "Install the required tools and set up your development environment for this course.",
    "thumbnail": "/assets/images/lesson/lesson_009_thumbnail.png",
    "videoUrl": "/videos/course_002/lesson_009.mp4",
    "duration": "18:01",
    "order": 2,
    "isPreview": true,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_002",
    "lessonCode": "lesson_010",
    "lessonNumber": 3,
    "title": "Understand the core concepts behind Fabric and TurboModules",
    "description": "Hands-on lesson covering: understand the core concepts behind Fabric and TurboModules.",
    "thumbnail": "/assets/images/lesson/lesson_010_thumbnail.png",
    "videoUrl": "/videos/course_002/lesson_010.mp4",
    "duration": "20:04",
    "order": 3,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_002",
    "lessonCode": "lesson_011",
    "lessonNumber": 4,
    "title": "Migrate a legacy React Native app to the New Architecture",
    "description": "Hands-on lesson covering: migrate a legacy React Native app to the New Architecture.",
    "thumbnail": "/assets/images/lesson/lesson_011_thumbnail.png",
    "videoUrl": "/videos/course_002/lesson_011.mp4",
    "duration": "24:16",
    "order": 4,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_002",
    "lessonCode": "lesson_012",
    "lessonNumber": 5,
    "title": "Write custom native modules using the new bridge",
    "description": "Hands-on lesson covering: write custom native modules using the new bridge.",
    "thumbnail": "/assets/images/lesson/lesson_012_thumbnail.png",
    "videoUrl": "/videos/course_002/lesson_012.mp4",
    "duration": "27:38",
    "order": 5,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_002",
    "lessonCode": "lesson_013",
    "lessonNumber": 6,
    "title": "Improve rendering performance with the new architecture",
    "description": "Hands-on lesson covering: improve rendering performance with the new architecture.",
    "thumbnail": "/assets/images/lesson/lesson_013_thumbnail.png",
    "videoUrl": "/videos/course_002/lesson_013.mp4",
    "duration": "29:17",
    "order": 6,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_002",
    "lessonCode": "lesson_014",
    "lessonNumber": 7,
    "title": "Troubleshoot common migration issues",
    "description": "Hands-on lesson covering: troubleshoot common migration issues.",
    "thumbnail": "/assets/images/lesson/lesson_014_thumbnail.png",
    "videoUrl": "/videos/course_002/lesson_014.mp4",
    "duration": "22:47",
    "order": 7,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_003",
    "lessonCode": "lesson_015",
    "lessonNumber": 1,
    "title": "Welcome to Redux Toolkit Complete Guide",
    "description": "Course introduction, roadmap, and what you'll build by the end of \"Redux Toolkit Complete Guide\".",
    "thumbnail": "/assets/images/lesson/lesson_015_thumbnail.png",
    "videoUrl": "/videos/course_003/lesson_015.mp4",
    "duration": "06:29",
    "order": 1,
    "isPreview": true,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_003",
    "lessonCode": "lesson_016",
    "lessonNumber": 2,
    "title": "Setting Up Your React Native Environment",
    "description": "Install the required tools and set up your development environment for this course.",
    "thumbnail": "/assets/images/lesson/lesson_016_thumbnail.png",
    "videoUrl": "/videos/course_003/lesson_016.mp4",
    "duration": "14:31",
    "order": 2,
    "isPreview": true,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_003",
    "lessonCode": "lesson_017",
    "lessonNumber": 3,
    "title": "Set up Redux Toolkit in a React Native project",
    "description": "Hands-on lesson covering: set up Redux Toolkit in a React Native project.",
    "thumbnail": "/assets/images/lesson/lesson_017_thumbnail.png",
    "videoUrl": "/videos/course_003/lesson_017.mp4",
    "duration": "21:40",
    "order": 3,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_003",
    "lessonCode": "lesson_018",
    "lessonNumber": 4,
    "title": "Create slices, reducers, and actions the modern way",
    "description": "Hands-on lesson covering: create slices, reducers, and actions the modern way.",
    "thumbnail": "/assets/images/lesson/lesson_018_thumbnail.png",
    "videoUrl": "/videos/course_003/lesson_018.mp4",
    "duration": "23:45",
    "order": 4,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_003",
    "lessonCode": "lesson_019",
    "lessonNumber": 5,
    "title": "Handle async data fetching with createAsyncThunk",
    "description": "Hands-on lesson covering: handle async data fetching with createAsyncThunk.",
    "thumbnail": "/assets/images/lesson/lesson_019_thumbnail.png",
    "videoUrl": "/videos/course_003/lesson_019.mp4",
    "duration": "18:51",
    "order": 5,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_003",
    "lessonCode": "lesson_020",
    "lessonNumber": 6,
    "title": "Connect Redux state to components efficiently",
    "description": "Hands-on lesson covering: connect Redux state to components efficiently.",
    "thumbnail": "/assets/images/lesson/lesson_020_thumbnail.png",
    "videoUrl": "/videos/course_003/lesson_020.mp4",
    "duration": "27:11",
    "order": 6,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_003",
    "lessonCode": "lesson_021",
    "lessonNumber": 7,
    "title": "Debug state with Redux DevTools",
    "description": "Hands-on lesson covering: debug state with Redux DevTools.",
    "thumbnail": "/assets/images/lesson/lesson_021_thumbnail.png",
    "videoUrl": "/videos/course_003/lesson_021.mp4",
    "duration": "16:45",
    "order": 7,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_004",
    "lessonCode": "lesson_022",
    "lessonNumber": 1,
    "title": "Welcome to Node.js & Express API Development",
    "description": "Course introduction, roadmap, and what you'll build by the end of \"Node.js & Express API Development\".",
    "thumbnail": "/assets/images/lesson/lesson_022_thumbnail.png",
    "videoUrl": "/videos/course_004/lesson_022.mp4",
    "duration": "08:54",
    "order": 1,
    "isPreview": true,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_004",
    "lessonCode": "lesson_023",
    "lessonNumber": 2,
    "title": "Setting Up Your Node.js Environment",
    "description": "Install the required tools and set up your development environment for this course.",
    "thumbnail": "/assets/images/lesson/lesson_023_thumbnail.png",
    "videoUrl": "/videos/course_004/lesson_023.mp4",
    "duration": "10:23",
    "order": 2,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_004",
    "lessonCode": "lesson_024",
    "lessonNumber": 3,
    "title": "Design and structure a Node.js and Express project",
    "description": "Hands-on lesson covering: design and structure a Node.js and Express project.",
    "thumbnail": "/assets/images/lesson/lesson_024_thumbnail.png",
    "videoUrl": "/videos/course_004/lesson_024.mp4",
    "duration": "19:44",
    "order": 3,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_004",
    "lessonCode": "lesson_025",
    "lessonNumber": 4,
    "title": "Build RESTful routes and middleware pipelines",
    "description": "Hands-on lesson covering: build RESTful routes and middleware pipelines.",
    "thumbnail": "/assets/images/lesson/lesson_025_thumbnail.png",
    "videoUrl": "/videos/course_004/lesson_025.mp4",
    "duration": "21:36",
    "order": 4,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_004",
    "lessonCode": "lesson_026",
    "lessonNumber": 5,
    "title": "Implement authentication and authorization",
    "description": "Hands-on lesson covering: implement authentication and authorization.",
    "thumbnail": "/assets/images/lesson/lesson_026_thumbnail.png",
    "videoUrl": "/videos/course_004/lesson_026.mp4",
    "duration": "23:06",
    "order": 5,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_004",
    "lessonCode": "lesson_027",
    "lessonNumber": 6,
    "title": "Handle errors and validate incoming requests",
    "description": "Hands-on lesson covering: handle errors and validate incoming requests.",
    "thumbnail": "/assets/images/lesson/lesson_027_thumbnail.png",
    "videoUrl": "/videos/course_004/lesson_027.mp4",
    "duration": "23:55",
    "order": 6,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_004",
    "lessonCode": "lesson_028",
    "lessonNumber": 7,
    "title": "Deploy and scale a Node.js API",
    "description": "Hands-on lesson covering: deploy and scale a Node.js API.",
    "thumbnail": "/assets/images/lesson/lesson_028_thumbnail.png",
    "videoUrl": "/videos/course_004/lesson_028.mp4",
    "duration": "24:48",
    "order": 7,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_005",
    "lessonCode": "lesson_029",
    "lessonNumber": 1,
    "title": "Welcome to MongoDB From Scratch",
    "description": "Course introduction, roadmap, and what you'll build by the end of \"MongoDB From Scratch\".",
    "thumbnail": "/assets/images/lesson/lesson_029_thumbnail.png",
    "videoUrl": "/videos/course_005/lesson_029.mp4",
    "duration": "08:40",
    "order": 1,
    "isPreview": true,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_005",
    "lessonCode": "lesson_030",
    "lessonNumber": 2,
    "title": "Setting Up Your MongoDB Environment",
    "description": "Install the required tools and set up your development environment for this course.",
    "thumbnail": "/assets/images/lesson/lesson_030_thumbnail.png",
    "videoUrl": "/videos/course_005/lesson_030.mp4",
    "duration": "13:42",
    "order": 2,
    "isPreview": true,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_005",
    "lessonCode": "lesson_031",
    "lessonNumber": 3,
    "title": "Install and configure MongoDB for development",
    "description": "Hands-on lesson covering: install and configure MongoDB for development.",
    "thumbnail": "/assets/images/lesson/lesson_031_thumbnail.png",
    "videoUrl": "/videos/course_005/lesson_031.mp4",
    "duration": "27:33",
    "order": 3,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_005",
    "lessonCode": "lesson_032",
    "lessonNumber": 4,
    "title": "Perform CRUD operations with the MongoDB driver",
    "description": "Hands-on lesson covering: perform CRUD operations with the MongoDB driver.",
    "thumbnail": "/assets/images/lesson/lesson_032_thumbnail.png",
    "videoUrl": "/videos/course_005/lesson_032.mp4",
    "duration": "15:34",
    "order": 4,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_005",
    "lessonCode": "lesson_033",
    "lessonNumber": 5,
    "title": "Design efficient, scalable document schemas",
    "description": "Hands-on lesson covering: design efficient, scalable document schemas.",
    "thumbnail": "/assets/images/lesson/lesson_033_thumbnail.png",
    "videoUrl": "/videos/course_005/lesson_033.mp4",
    "duration": "15:56",
    "order": 5,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_005",
    "lessonCode": "lesson_034",
    "lessonNumber": 6,
    "title": "Use indexes to improve query performance",
    "description": "Hands-on lesson covering: use indexes to improve query performance.",
    "thumbnail": "/assets/images/lesson/lesson_034_thumbnail.png",
    "videoUrl": "/videos/course_005/lesson_034.mp4",
    "duration": "21:06",
    "order": 6,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_005",
    "lessonCode": "lesson_035",
    "lessonNumber": 7,
    "title": "Build aggregation pipelines for data analysis",
    "description": "Hands-on lesson covering: build aggregation pipelines for data analysis.",
    "thumbnail": "/assets/images/lesson/lesson_035_thumbnail.png",
    "videoUrl": "/videos/course_005/lesson_035.mp4",
    "duration": "27:59",
    "order": 7,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_006",
    "lessonCode": "lesson_036",
    "lessonNumber": 1,
    "title": "Welcome to Modern JavaScript",
    "description": "Course introduction, roadmap, and what you'll build by the end of \"Modern JavaScript\".",
    "thumbnail": "/assets/images/lesson/lesson_036_thumbnail.png",
    "videoUrl": "/videos/course_006/lesson_036.mp4",
    "duration": "05:25",
    "order": 1,
    "isPreview": true,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_006",
    "lessonCode": "lesson_037",
    "lessonNumber": 2,
    "title": "Setting Up Your React Environment",
    "description": "Install the required tools and set up your development environment for this course.",
    "thumbnail": "/assets/images/lesson/lesson_037_thumbnail.png",
    "videoUrl": "/videos/course_006/lesson_037.mp4",
    "duration": "17:48",
    "order": 2,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_006",
    "lessonCode": "lesson_038",
    "lessonNumber": 3,
    "title": "Master ES6+ syntax including destructuring and spread operators",
    "description": "Hands-on lesson covering: master ES6+ syntax including destructuring and spread operators.",
    "thumbnail": "/assets/images/lesson/lesson_038_thumbnail.png",
    "videoUrl": "/videos/course_006/lesson_038.mp4",
    "duration": "24:33",
    "order": 3,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_006",
    "lessonCode": "lesson_039",
    "lessonNumber": 4,
    "title": "Understand closures, scope, and the 'this' keyword",
    "description": "Hands-on lesson covering: understand closures, scope, and the 'this' keyword.",
    "thumbnail": "/assets/images/lesson/lesson_039_thumbnail.png",
    "videoUrl": "/videos/course_006/lesson_039.mp4",
    "duration": "27:48",
    "order": 4,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_006",
    "lessonCode": "lesson_040",
    "lessonNumber": 5,
    "title": "Work confidently with promises and async/await",
    "description": "Hands-on lesson covering: work confidently with promises and async/await.",
    "thumbnail": "/assets/images/lesson/lesson_040_thumbnail.png",
    "videoUrl": "/videos/course_006/lesson_040.mp4",
    "duration": "20:36",
    "order": 5,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_006",
    "lessonCode": "lesson_041",
    "lessonNumber": 6,
    "title": "Apply functional programming patterns in JavaScript",
    "description": "Hands-on lesson covering: apply functional programming patterns in JavaScript.",
    "thumbnail": "/assets/images/lesson/lesson_041_thumbnail.png",
    "videoUrl": "/videos/course_006/lesson_041.mp4",
    "duration": "26:29",
    "order": 6,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_006",
    "lessonCode": "lesson_042",
    "lessonNumber": 7,
    "title": "Write cleaner, more maintainable modern JavaScript",
    "description": "Hands-on lesson covering: write cleaner, more maintainable modern JavaScript.",
    "thumbnail": "/assets/images/lesson/lesson_042_thumbnail.png",
    "videoUrl": "/videos/course_006/lesson_042.mp4",
    "duration": "26:49",
    "order": 7,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_007",
    "lessonCode": "lesson_043",
    "lessonNumber": 1,
    "title": "Welcome to TypeScript Bootcamp",
    "description": "Course introduction, roadmap, and what you'll build by the end of \"TypeScript Bootcamp\".",
    "thumbnail": "/assets/images/lesson/lesson_043_thumbnail.png",
    "videoUrl": "/videos/course_007/lesson_043.mp4",
    "duration": "08:00",
    "order": 1,
    "isPreview": true,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_007",
    "lessonCode": "lesson_044",
    "lessonNumber": 2,
    "title": "Setting Up Your React Environment",
    "description": "Install the required tools and set up your development environment for this course.",
    "thumbnail": "/assets/images/lesson/lesson_044_thumbnail.png",
    "videoUrl": "/videos/course_007/lesson_044.mp4",
    "duration": "16:42",
    "order": 2,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_007",
    "lessonCode": "lesson_045",
    "lessonNumber": 3,
    "title": "Understand TypeScript's type system and core syntax",
    "description": "Hands-on lesson covering: understand TypeScript's type system and core syntax.",
    "thumbnail": "/assets/images/lesson/lesson_045_thumbnail.png",
    "videoUrl": "/videos/course_007/lesson_045.mp4",
    "duration": "19:33",
    "order": 3,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_007",
    "lessonCode": "lesson_046",
    "lessonNumber": 4,
    "title": "Use interfaces, generics, and utility types effectively",
    "description": "Hands-on lesson covering: use interfaces, generics, and utility types effectively.",
    "thumbnail": "/assets/images/lesson/lesson_046_thumbnail.png",
    "videoUrl": "/videos/course_007/lesson_046.mp4",
    "duration": "28:17",
    "order": 4,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_007",
    "lessonCode": "lesson_047",
    "lessonNumber": 5,
    "title": "Migrate a JavaScript project to TypeScript",
    "description": "Hands-on lesson covering: migrate a JavaScript project to TypeScript.",
    "thumbnail": "/assets/images/lesson/lesson_047_thumbnail.png",
    "videoUrl": "/videos/course_007/lesson_047.mp4",
    "duration": "26:31",
    "order": 5,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_007",
    "lessonCode": "lesson_048",
    "lessonNumber": 6,
    "title": "Configure the TypeScript compiler for real projects",
    "description": "Hands-on lesson covering: configure the TypeScript compiler for real projects.",
    "thumbnail": "/assets/images/lesson/lesson_048_thumbnail.png",
    "videoUrl": "/videos/course_007/lesson_048.mp4",
    "duration": "27:14",
    "order": 6,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_007",
    "lessonCode": "lesson_049",
    "lessonNumber": 7,
    "title": "Apply type-safe patterns in React applications",
    "description": "Hands-on lesson covering: apply type-safe patterns in React applications.",
    "thumbnail": "/assets/images/lesson/lesson_049_thumbnail.png",
    "videoUrl": "/videos/course_007/lesson_049.mp4",
    "duration": "24:35",
    "order": 7,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_008",
    "lessonCode": "lesson_050",
    "lessonNumber": 1,
    "title": "Welcome to React.js Complete Course",
    "description": "Course introduction, roadmap, and what you'll build by the end of \"React.js Complete Course\".",
    "thumbnail": "/assets/images/lesson/lesson_050_thumbnail.png",
    "videoUrl": "/videos/course_008/lesson_050.mp4",
    "duration": "07:22",
    "order": 1,
    "isPreview": true,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_008",
    "lessonCode": "lesson_051",
    "lessonNumber": 2,
    "title": "Setting Up Your React Environment",
    "description": "Install the required tools and set up your development environment for this course.",
    "thumbnail": "/assets/images/lesson/lesson_051_thumbnail.png",
    "videoUrl": "/videos/course_008/lesson_051.mp4",
    "duration": "17:26",
    "order": 2,
    "isPreview": true,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_008",
    "lessonCode": "lesson_052",
    "lessonNumber": 3,
    "title": "Build reusable components with React and JSX",
    "description": "Hands-on lesson covering: build reusable components with React and JSX.",
    "thumbnail": "/assets/images/lesson/lesson_052_thumbnail.png",
    "videoUrl": "/videos/course_008/lesson_052.mp4",
    "duration": "19:10",
    "order": 3,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_008",
    "lessonCode": "lesson_053",
    "lessonNumber": 4,
    "title": "Manage component state and side effects with hooks",
    "description": "Hands-on lesson covering: manage component state and side effects with hooks.",
    "thumbnail": "/assets/images/lesson/lesson_053_thumbnail.png",
    "videoUrl": "/videos/course_008/lesson_053.mp4",
    "duration": "18:04",
    "order": 4,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_008",
    "lessonCode": "lesson_054",
    "lessonNumber": 5,
    "title": "Implement client-side routing with React Router",
    "description": "Hands-on lesson covering: implement client-side routing with React Router.",
    "thumbnail": "/assets/images/lesson/lesson_054_thumbnail.png",
    "videoUrl": "/videos/course_008/lesson_054.mp4",
    "duration": "22:31",
    "order": 5,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_008",
    "lessonCode": "lesson_055",
    "lessonNumber": 6,
    "title": "Fetch and display data from external APIs",
    "description": "Hands-on lesson covering: fetch and display data from external APIs.",
    "thumbnail": "/assets/images/lesson/lesson_055_thumbnail.png",
    "videoUrl": "/videos/course_008/lesson_055.mp4",
    "duration": "18:18",
    "order": 6,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_008",
    "lessonCode": "lesson_056",
    "lessonNumber": 7,
    "title": "Structure and deploy a complete React application",
    "description": "Hands-on lesson covering: structure and deploy a complete React application.",
    "thumbnail": "/assets/images/lesson/lesson_056_thumbnail.png",
    "videoUrl": "/videos/course_008/lesson_056.mp4",
    "duration": "20:40",
    "order": 7,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_009",
    "lessonCode": "lesson_057",
    "lessonNumber": 1,
    "title": "Welcome to Kotlin for Android",
    "description": "Course introduction, roadmap, and what you'll build by the end of \"Kotlin for Android\".",
    "thumbnail": "/assets/images/lesson/lesson_057_thumbnail.png",
    "videoUrl": "/videos/course_009/lesson_057.mp4",
    "duration": "07:32",
    "order": 1,
    "isPreview": true,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_009",
    "lessonCode": "lesson_058",
    "lessonNumber": 2,
    "title": "Setting Up Your Android Environment",
    "description": "Install the required tools and set up your development environment for this course.",
    "thumbnail": "/assets/images/lesson/lesson_058_thumbnail.png",
    "videoUrl": "/videos/course_009/lesson_058.mp4",
    "duration": "18:50",
    "order": 2,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_009",
    "lessonCode": "lesson_059",
    "lessonNumber": 3,
    "title": "Write idiomatic Kotlin code for Android",
    "description": "Hands-on lesson covering: write idiomatic Kotlin code for Android.",
    "thumbnail": "/assets/images/lesson/lesson_059_thumbnail.png",
    "videoUrl": "/videos/course_009/lesson_059.mp4",
    "duration": "21:09",
    "order": 3,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_009",
    "lessonCode": "lesson_060",
    "lessonNumber": 4,
    "title": "Understand Kotlin's null safety and coroutines",
    "description": "Hands-on lesson covering: understand Kotlin's null safety and coroutines.",
    "thumbnail": "/assets/images/lesson/lesson_060_thumbnail.png",
    "videoUrl": "/videos/course_009/lesson_060.mp4",
    "duration": "17:39",
    "order": 4,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_009",
    "lessonCode": "lesson_061",
    "lessonNumber": 5,
    "title": "Build Android UIs using Kotlin",
    "description": "Hands-on lesson covering: build Android UIs using Kotlin.",
    "thumbnail": "/assets/images/lesson/lesson_061_thumbnail.png",
    "videoUrl": "/videos/course_009/lesson_061.mp4",
    "duration": "25:14",
    "order": 5,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_009",
    "lessonCode": "lesson_062",
    "lessonNumber": 6,
    "title": "Work with Android Architecture Components",
    "description": "Hands-on lesson covering: work with Android Architecture Components.",
    "thumbnail": "/assets/images/lesson/lesson_062_thumbnail.png",
    "videoUrl": "/videos/course_009/lesson_062.mp4",
    "duration": "25:46",
    "order": 6,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_009",
    "lessonCode": "lesson_063",
    "lessonNumber": 7,
    "title": "Structure and test a Kotlin-based Android app",
    "description": "Hands-on lesson covering: structure and test a Kotlin-based Android app.",
    "thumbnail": "/assets/images/lesson/lesson_063_thumbnail.png",
    "videoUrl": "/videos/course_009/lesson_063.mp4",
    "duration": "28:56",
    "order": 7,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_010",
    "lessonCode": "lesson_064",
    "lessonNumber": 1,
    "title": "Welcome to SwiftUI Essentials",
    "description": "Course introduction, roadmap, and what you'll build by the end of \"SwiftUI Essentials\".",
    "thumbnail": "/assets/images/lesson/lesson_064_thumbnail.png",
    "videoUrl": "/videos/course_010/lesson_064.mp4",
    "duration": "05:10",
    "order": 1,
    "isPreview": true,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_010",
    "lessonCode": "lesson_065",
    "lessonNumber": 2,
    "title": "Setting Up Your SwiftUI Environment",
    "description": "Install the required tools and set up your development environment for this course.",
    "thumbnail": "/assets/images/lesson/lesson_065_thumbnail.png",
    "videoUrl": "/videos/course_010/lesson_065.mp4",
    "duration": "17:10",
    "order": 2,
    "isPreview": true,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_010",
    "lessonCode": "lesson_066",
    "lessonNumber": 3,
    "title": "Understand SwiftUI's declarative syntax and view system",
    "description": "Hands-on lesson covering: understand SwiftUI's declarative syntax and view system.",
    "thumbnail": "/assets/images/lesson/lesson_066_thumbnail.png",
    "videoUrl": "/videos/course_010/lesson_066.mp4",
    "duration": "17:40",
    "order": 3,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_010",
    "lessonCode": "lesson_067",
    "lessonNumber": 4,
    "title": "Manage state with @State, @Binding, and @ObservedObject",
    "description": "Hands-on lesson covering: manage state with @State, @Binding, and @ObservedObject.",
    "thumbnail": "/assets/images/lesson/lesson_067_thumbnail.png",
    "videoUrl": "/videos/course_010/lesson_067.mp4",
    "duration": "20:21",
    "order": 4,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_010",
    "lessonCode": "lesson_068",
    "lessonNumber": 5,
    "title": "Build navigation flows and lists in SwiftUI",
    "description": "Hands-on lesson covering: build navigation flows and lists in SwiftUI.",
    "thumbnail": "/assets/images/lesson/lesson_068_thumbnail.png",
    "videoUrl": "/videos/course_010/lesson_068.mp4",
    "duration": "27:23",
    "order": 5,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_010",
    "lessonCode": "lesson_069",
    "lessonNumber": 6,
    "title": "Style and animate SwiftUI views",
    "description": "Hands-on lesson covering: style and animate SwiftUI views.",
    "thumbnail": "/assets/images/lesson/lesson_069_thumbnail.png",
    "videoUrl": "/videos/course_010/lesson_069.mp4",
    "duration": "20:07",
    "order": 6,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_010",
    "lessonCode": "lesson_070",
    "lessonNumber": 7,
    "title": "Build and preview a complete iOS app UI",
    "description": "Hands-on lesson covering: build and preview a complete iOS app UI.",
    "thumbnail": "/assets/images/lesson/lesson_070_thumbnail.png",
    "videoUrl": "/videos/course_010/lesson_070.mp4",
    "duration": "15:59",
    "order": 7,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_011",
    "lessonCode": "lesson_071",
    "lessonNumber": 1,
    "title": "Welcome to Android Jetpack Compose",
    "description": "Course introduction, roadmap, and what you'll build by the end of \"Android Jetpack Compose\".",
    "thumbnail": "/assets/images/lesson/lesson_071_thumbnail.png",
    "videoUrl": "/videos/course_011/lesson_071.mp4",
    "duration": "07:18",
    "order": 1,
    "isPreview": true,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_011",
    "lessonCode": "lesson_072",
    "lessonNumber": 2,
    "title": "Setting Up Your Android Environment",
    "description": "Install the required tools and set up your development environment for this course.",
    "thumbnail": "/assets/images/lesson/lesson_072_thumbnail.png",
    "videoUrl": "/videos/course_011/lesson_072.mp4",
    "duration": "18:21",
    "order": 2,
    "isPreview": true,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_011",
    "lessonCode": "lesson_073",
    "lessonNumber": 3,
    "title": "Understand Compose's declarative UI model",
    "description": "Hands-on lesson covering: understand Compose's declarative UI model.",
    "thumbnail": "/assets/images/lesson/lesson_073_thumbnail.png",
    "videoUrl": "/videos/course_011/lesson_073.mp4",
    "duration": "23:40",
    "order": 3,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_011",
    "lessonCode": "lesson_074",
    "lessonNumber": 4,
    "title": "Build layouts using Composable functions",
    "description": "Hands-on lesson covering: build layouts using Composable functions.",
    "thumbnail": "/assets/images/lesson/lesson_074_thumbnail.png",
    "videoUrl": "/videos/course_011/lesson_074.mp4",
    "duration": "15:32",
    "order": 4,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_011",
    "lessonCode": "lesson_075",
    "lessonNumber": 5,
    "title": "Manage UI state within Compose",
    "description": "Hands-on lesson covering: manage UI state within Compose.",
    "thumbnail": "/assets/images/lesson/lesson_075_thumbnail.png",
    "videoUrl": "/videos/course_011/lesson_075.mp4",
    "duration": "16:09",
    "order": 5,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_011",
    "lessonCode": "lesson_076",
    "lessonNumber": 6,
    "title": "Handle navigation in a Compose-based app",
    "description": "Hands-on lesson covering: handle navigation in a Compose-based app.",
    "thumbnail": "/assets/images/lesson/lesson_076_thumbnail.png",
    "videoUrl": "/videos/course_011/lesson_076.mp4",
    "duration": "19:38",
    "order": 6,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_011",
    "lessonCode": "lesson_077",
    "lessonNumber": 7,
    "title": "Style and theme apps using Material 3",
    "description": "Hands-on lesson covering: style and theme apps using Material 3.",
    "thumbnail": "/assets/images/lesson/lesson_077_thumbnail.png",
    "videoUrl": "/videos/course_011/lesson_077.mp4",
    "duration": "29:33",
    "order": 7,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_012",
    "lessonCode": "lesson_078",
    "lessonNumber": 1,
    "title": "Welcome to Firebase for Mobile Apps",
    "description": "Course introduction, roadmap, and what you'll build by the end of \"Firebase for Mobile Apps\".",
    "thumbnail": "/assets/images/lesson/lesson_078_thumbnail.png",
    "videoUrl": "/videos/course_012/lesson_078.mp4",
    "duration": "07:25",
    "order": 1,
    "isPreview": true,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_012",
    "lessonCode": "lesson_079",
    "lessonNumber": 2,
    "title": "Setting Up Your Node.js Environment",
    "description": "Install the required tools and set up your development environment for this course.",
    "thumbnail": "/assets/images/lesson/lesson_079_thumbnail.png",
    "videoUrl": "/videos/course_012/lesson_079.mp4",
    "duration": "16:47",
    "order": 2,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_012",
    "lessonCode": "lesson_080",
    "lessonNumber": 3,
    "title": "Set up Firebase in a mobile application",
    "description": "Hands-on lesson covering: set up Firebase in a mobile application.",
    "thumbnail": "/assets/images/lesson/lesson_080_thumbnail.png",
    "videoUrl": "/videos/course_012/lesson_080.mp4",
    "duration": "25:13",
    "order": 3,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_012",
    "lessonCode": "lesson_081",
    "lessonNumber": 4,
    "title": "Implement authentication with Firebase Auth",
    "description": "Hands-on lesson covering: implement authentication with Firebase Auth.",
    "thumbnail": "/assets/images/lesson/lesson_081_thumbnail.png",
    "videoUrl": "/videos/course_012/lesson_081.mp4",
    "duration": "22:04",
    "order": 4,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_012",
    "lessonCode": "lesson_082",
    "lessonNumber": 5,
    "title": "Read and write data with Firestore in real time",
    "description": "Hands-on lesson covering: read and write data with Firestore in real time.",
    "thumbnail": "/assets/images/lesson/lesson_082_thumbnail.png",
    "videoUrl": "/videos/course_012/lesson_082.mp4",
    "duration": "16:30",
    "order": 5,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_012",
    "lessonCode": "lesson_083",
    "lessonNumber": 6,
    "title": "Store and retrieve files with Firebase Storage",
    "description": "Hands-on lesson covering: store and retrieve files with Firebase Storage.",
    "thumbnail": "/assets/images/lesson/lesson_083_thumbnail.png",
    "videoUrl": "/videos/course_012/lesson_083.mp4",
    "duration": "23:45",
    "order": 6,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_012",
    "lessonCode": "lesson_084",
    "lessonNumber": 7,
    "title": "Send push notifications with Firebase Cloud Messaging",
    "description": "Hands-on lesson covering: send push notifications with Firebase Cloud Messaging.",
    "thumbnail": "/assets/images/lesson/lesson_084_thumbnail.png",
    "videoUrl": "/videos/course_012/lesson_084.mp4",
    "duration": "21:50",
    "order": 7,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_013",
    "lessonCode": "lesson_085",
    "lessonNumber": 1,
    "title": "Welcome to Git & GitHub Masterclass",
    "description": "Course introduction, roadmap, and what you'll build by the end of \"Git & GitHub Masterclass\".",
    "thumbnail": "/assets/images/lesson/lesson_085_thumbnail.png",
    "videoUrl": "/videos/course_013/lesson_085.mp4",
    "duration": "09:57",
    "order": 1,
    "isPreview": true,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_013",
    "lessonCode": "lesson_086",
    "lessonNumber": 2,
    "title": "Setting Up Your Git Environment",
    "description": "Install the required tools and set up your development environment for this course.",
    "thumbnail": "/assets/images/lesson/lesson_086_thumbnail.png",
    "videoUrl": "/videos/course_013/lesson_086.mp4",
    "duration": "10:57",
    "order": 2,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_013",
    "lessonCode": "lesson_087",
    "lessonNumber": 3,
    "title": "Understand core Git concepts: commits, branches, and merges",
    "description": "Hands-on lesson covering: understand core Git concepts: commits, branches, and merges.",
    "thumbnail": "/assets/images/lesson/lesson_087_thumbnail.png",
    "videoUrl": "/videos/course_013/lesson_087.mp4",
    "duration": "27:50",
    "order": 3,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_013",
    "lessonCode": "lesson_088",
    "lessonNumber": 4,
    "title": "Resolve merge conflicts confidently",
    "description": "Hands-on lesson covering: resolve merge conflicts confidently.",
    "thumbnail": "/assets/images/lesson/lesson_088_thumbnail.png",
    "videoUrl": "/videos/course_013/lesson_088.mp4",
    "duration": "26:33",
    "order": 4,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_013",
    "lessonCode": "lesson_089",
    "lessonNumber": 5,
    "title": "Collaborate on GitHub using pull requests and reviews",
    "description": "Hands-on lesson covering: collaborate on GitHub using pull requests and reviews.",
    "thumbnail": "/assets/images/lesson/lesson_089_thumbnail.png",
    "videoUrl": "/videos/course_013/lesson_089.mp4",
    "duration": "24:28",
    "order": 5,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_013",
    "lessonCode": "lesson_090",
    "lessonNumber": 6,
    "title": "Use branching strategies for team projects",
    "description": "Hands-on lesson covering: use branching strategies for team projects.",
    "thumbnail": "/assets/images/lesson/lesson_090_thumbnail.png",
    "videoUrl": "/videos/course_013/lesson_090.mp4",
    "duration": "16:17",
    "order": 6,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_013",
    "lessonCode": "lesson_091",
    "lessonNumber": 7,
    "title": "Recover from mistakes using Git history",
    "description": "Hands-on lesson covering: recover from mistakes using Git history.",
    "thumbnail": "/assets/images/lesson/lesson_091_thumbnail.png",
    "videoUrl": "/videos/course_013/lesson_091.mp4",
    "duration": "27:46",
    "order": 7,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_014",
    "lessonCode": "lesson_092",
    "lessonNumber": 1,
    "title": "Welcome to REST API Design",
    "description": "Course introduction, roadmap, and what you'll build by the end of \"REST API Design\".",
    "thumbnail": "/assets/images/lesson/lesson_092_thumbnail.png",
    "videoUrl": "/videos/course_014/lesson_092.mp4",
    "duration": "08:03",
    "order": 1,
    "isPreview": true,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_014",
    "lessonCode": "lesson_093",
    "lessonNumber": 2,
    "title": "Setting Up Your Node.js Environment",
    "description": "Install the required tools and set up your development environment for this course.",
    "thumbnail": "/assets/images/lesson/lesson_093_thumbnail.png",
    "videoUrl": "/videos/course_014/lesson_093.mp4",
    "duration": "15:38",
    "order": 2,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_014",
    "lessonCode": "lesson_094",
    "lessonNumber": 3,
    "title": "Design resource-oriented, RESTful endpoints",
    "description": "Hands-on lesson covering: design resource-oriented, RESTful endpoints.",
    "thumbnail": "/assets/images/lesson/lesson_094_thumbnail.png",
    "videoUrl": "/videos/course_014/lesson_094.mp4",
    "duration": "24:47",
    "order": 3,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_014",
    "lessonCode": "lesson_095",
    "lessonNumber": 4,
    "title": "Apply proper HTTP methods and status codes",
    "description": "Hands-on lesson covering: apply proper HTTP methods and status codes.",
    "thumbnail": "/assets/images/lesson/lesson_095_thumbnail.png",
    "videoUrl": "/videos/course_014/lesson_095.mp4",
    "duration": "21:43",
    "order": 4,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_014",
    "lessonCode": "lesson_096",
    "lessonNumber": 5,
    "title": "Version and document APIs effectively",
    "description": "Hands-on lesson covering: version and document APIs effectively.",
    "thumbnail": "/assets/images/lesson/lesson_096_thumbnail.png",
    "videoUrl": "/videos/course_014/lesson_096.mp4",
    "duration": "25:35",
    "order": 5,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_014",
    "lessonCode": "lesson_097",
    "lessonNumber": 6,
    "title": "Implement pagination, filtering, and sorting",
    "description": "Hands-on lesson covering: implement pagination, filtering, and sorting.",
    "thumbnail": "/assets/images/lesson/lesson_097_thumbnail.png",
    "videoUrl": "/videos/course_014/lesson_097.mp4",
    "duration": "23:51",
    "order": 6,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_014",
    "lessonCode": "lesson_098",
    "lessonNumber": 7,
    "title": "Secure APIs with authentication best practices",
    "description": "Hands-on lesson covering: secure APIs with authentication best practices.",
    "thumbnail": "/assets/images/lesson/lesson_098_thumbnail.png",
    "videoUrl": "/videos/course_014/lesson_098.mp4",
    "duration": "23:25",
    "order": 7,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_015",
    "lessonCode": "lesson_099",
    "lessonNumber": 1,
    "title": "Welcome to Docker Fundamentals",
    "description": "Course introduction, roadmap, and what you'll build by the end of \"Docker Fundamentals\".",
    "thumbnail": "/assets/images/lesson/lesson_099_thumbnail.png",
    "videoUrl": "/videos/course_015/lesson_099.mp4",
    "duration": "09:39",
    "order": 1,
    "isPreview": true,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_015",
    "lessonCode": "lesson_100",
    "lessonNumber": 2,
    "title": "Setting Up Your Docker Environment",
    "description": "Install the required tools and set up your development environment for this course.",
    "thumbnail": "/assets/images/lesson/lesson_100_thumbnail.png",
    "videoUrl": "/videos/course_015/lesson_100.mp4",
    "duration": "10:49",
    "order": 2,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_015",
    "lessonCode": "lesson_101",
    "lessonNumber": 3,
    "title": "Understand containers versus virtual machines",
    "description": "Hands-on lesson covering: understand containers versus virtual machines.",
    "thumbnail": "/assets/images/lesson/lesson_101_thumbnail.png",
    "videoUrl": "/videos/course_015/lesson_101.mp4",
    "duration": "20:30",
    "order": 3,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_015",
    "lessonCode": "lesson_102",
    "lessonNumber": 4,
    "title": "Build and manage Docker images with Dockerfiles",
    "description": "Hands-on lesson covering: build and manage Docker images with Dockerfiles.",
    "thumbnail": "/assets/images/lesson/lesson_102_thumbnail.png",
    "videoUrl": "/videos/course_015/lesson_102.mp4",
    "duration": "24:46",
    "order": 4,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_015",
    "lessonCode": "lesson_103",
    "lessonNumber": 5,
    "title": "Run and network multi-container apps with Docker Compose",
    "description": "Hands-on lesson covering: run and network multi-container apps with Docker Compose.",
    "thumbnail": "/assets/images/lesson/lesson_103_thumbnail.png",
    "videoUrl": "/videos/course_015/lesson_103.mp4",
    "duration": "23:09",
    "order": 5,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_015",
    "lessonCode": "lesson_104",
    "lessonNumber": 6,
    "title": "Persist data using Docker volumes",
    "description": "Hands-on lesson covering: persist data using Docker volumes.",
    "thumbnail": "/assets/images/lesson/lesson_104_thumbnail.png",
    "videoUrl": "/videos/course_015/lesson_104.mp4",
    "duration": "19:12",
    "order": 6,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_015",
    "lessonCode": "lesson_105",
    "lessonNumber": 7,
    "title": "Deploy containerized applications confidently",
    "description": "Hands-on lesson covering: deploy containerized applications confidently.",
    "thumbnail": "/assets/images/lesson/lesson_105_thumbnail.png",
    "videoUrl": "/videos/course_015/lesson_105.mp4",
    "duration": "19:18",
    "order": 7,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_016",
    "lessonCode": "lesson_106",
    "lessonNumber": 1,
    "title": "Welcome to UI Design with Figma",
    "description": "Course introduction, roadmap, and what you'll build by the end of \"UI Design with Figma\".",
    "thumbnail": "/assets/images/lesson/lesson_106_thumbnail.png",
    "videoUrl": "/videos/course_016/lesson_106.mp4",
    "duration": "06:57",
    "order": 1,
    "isPreview": true,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_016",
    "lessonCode": "lesson_107",
    "lessonNumber": 2,
    "title": "Setting Up Your Figma Environment",
    "description": "Install the required tools and set up your development environment for this course.",
    "thumbnail": "/assets/images/lesson/lesson_107_thumbnail.png",
    "videoUrl": "/videos/course_016/lesson_107.mp4",
    "duration": "17:12",
    "order": 2,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_016",
    "lessonCode": "lesson_108",
    "lessonNumber": 3,
    "title": "Navigate Figma's interface and core tools",
    "description": "Hands-on lesson covering: navigate Figma's interface and core tools.",
    "thumbnail": "/assets/images/lesson/lesson_108_thumbnail.png",
    "videoUrl": "/videos/course_016/lesson_108.mp4",
    "duration": "18:47",
    "order": 3,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_016",
    "lessonCode": "lesson_109",
    "lessonNumber": 4,
    "title": "Apply layout, typography, and color principles",
    "description": "Hands-on lesson covering: apply layout, typography, and color principles.",
    "thumbnail": "/assets/images/lesson/lesson_109_thumbnail.png",
    "videoUrl": "/videos/course_016/lesson_109.mp4",
    "duration": "15:37",
    "order": 4,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_016",
    "lessonCode": "lesson_110",
    "lessonNumber": 5,
    "title": "Build reusable components and design systems",
    "description": "Hands-on lesson covering: build reusable components and design systems.",
    "thumbnail": "/assets/images/lesson/lesson_110_thumbnail.png",
    "videoUrl": "/videos/course_016/lesson_110.mp4",
    "duration": "16:31",
    "order": 5,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_016",
    "lessonCode": "lesson_111",
    "lessonNumber": 6,
    "title": "Create interactive prototypes for user testing",
    "description": "Hands-on lesson covering: create interactive prototypes for user testing.",
    "thumbnail": "/assets/images/lesson/lesson_111_thumbnail.png",
    "videoUrl": "/videos/course_016/lesson_111.mp4",
    "duration": "29:30",
    "order": 6,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_016",
    "lessonCode": "lesson_112",
    "lessonNumber": 7,
    "title": "Hand off designs to developers effectively",
    "description": "Hands-on lesson covering: hand off designs to developers effectively.",
    "thumbnail": "/assets/images/lesson/lesson_112_thumbnail.png",
    "videoUrl": "/videos/course_016/lesson_112.mp4",
    "duration": "28:41",
    "order": 7,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_017",
    "lessonCode": "lesson_113",
    "lessonNumber": 1,
    "title": "Welcome to AI for Developers",
    "description": "Course introduction, roadmap, and what you'll build by the end of \"AI for Developers\".",
    "thumbnail": "/assets/images/lesson/lesson_113_thumbnail.png",
    "videoUrl": "/videos/course_017/lesson_113.mp4",
    "duration": "09:12",
    "order": 1,
    "isPreview": true,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_017",
    "lessonCode": "lesson_114",
    "lessonNumber": 2,
    "title": "Setting Up Your AI Environment",
    "description": "Install the required tools and set up your development environment for this course.",
    "thumbnail": "/assets/images/lesson/lesson_114_thumbnail.png",
    "videoUrl": "/videos/course_017/lesson_114.mp4",
    "duration": "18:27",
    "order": 2,
    "isPreview": true,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_017",
    "lessonCode": "lesson_115",
    "lessonNumber": 3,
    "title": "Understand core AI and machine learning concepts",
    "description": "Hands-on lesson covering: understand core AI and machine learning concepts.",
    "thumbnail": "/assets/images/lesson/lesson_115_thumbnail.png",
    "videoUrl": "/videos/course_017/lesson_115.mp4",
    "duration": "21:18",
    "order": 3,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_017",
    "lessonCode": "lesson_116",
    "lessonNumber": 4,
    "title": "Integrate AI APIs into applications",
    "description": "Hands-on lesson covering: integrate AI APIs into applications.",
    "thumbnail": "/assets/images/lesson/lesson_116_thumbnail.png",
    "videoUrl": "/videos/course_017/lesson_116.mp4",
    "duration": "20:22",
    "order": 4,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_017",
    "lessonCode": "lesson_117",
    "lessonNumber": 5,
    "title": "Work with prompts and language models effectively",
    "description": "Hands-on lesson covering: work with prompts and language models effectively.",
    "thumbnail": "/assets/images/lesson/lesson_117_thumbnail.png",
    "videoUrl": "/videos/course_017/lesson_117.mp4",
    "duration": "19:35",
    "order": 5,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_017",
    "lessonCode": "lesson_118",
    "lessonNumber": 6,
    "title": "Evaluate AI model outputs for reliability",
    "description": "Hands-on lesson covering: evaluate AI model outputs for reliability.",
    "thumbnail": "/assets/images/lesson/lesson_118_thumbnail.png",
    "videoUrl": "/videos/course_017/lesson_118.mp4",
    "duration": "29:42",
    "order": 6,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_017",
    "lessonCode": "lesson_119",
    "lessonNumber": 7,
    "title": "Build simple AI-powered features end to end",
    "description": "Hands-on lesson covering: build simple AI-powered features end to end.",
    "thumbnail": "/assets/images/lesson/lesson_119_thumbnail.png",
    "videoUrl": "/videos/course_017/lesson_119.mp4",
    "duration": "15:59",
    "order": 7,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_018",
    "lessonCode": "lesson_120",
    "lessonNumber": 1,
    "title": "Welcome to Machine Learning Basics",
    "description": "Course introduction, roadmap, and what you'll build by the end of \"Machine Learning Basics\".",
    "thumbnail": "/assets/images/lesson/lesson_120_thumbnail.png",
    "videoUrl": "/videos/course_018/lesson_120.mp4",
    "duration": "08:48",
    "order": 1,
    "isPreview": true,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_018",
    "lessonCode": "lesson_121",
    "lessonNumber": 2,
    "title": "Setting Up Your AI Environment",
    "description": "Install the required tools and set up your development environment for this course.",
    "thumbnail": "/assets/images/lesson/lesson_121_thumbnail.png",
    "videoUrl": "/videos/course_018/lesson_121.mp4",
    "duration": "10:06",
    "order": 2,
    "isPreview": true,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_018",
    "lessonCode": "lesson_122",
    "lessonNumber": 3,
    "title": "Understand core machine learning concepts and terminology",
    "description": "Hands-on lesson covering: understand core machine learning concepts and terminology.",
    "thumbnail": "/assets/images/lesson/lesson_122_thumbnail.png",
    "videoUrl": "/videos/course_018/lesson_122.mp4",
    "duration": "20:45",
    "order": 3,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_018",
    "lessonCode": "lesson_123",
    "lessonNumber": 4,
    "title": "Differentiate supervised and unsupervised learning",
    "description": "Hands-on lesson covering: differentiate supervised and unsupervised learning.",
    "thumbnail": "/assets/images/lesson/lesson_123_thumbnail.png",
    "videoUrl": "/videos/course_018/lesson_123.mp4",
    "duration": "24:31",
    "order": 4,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_018",
    "lessonCode": "lesson_124",
    "lessonNumber": 5,
    "title": "Train and evaluate simple ML models",
    "description": "Hands-on lesson covering: train and evaluate simple ML models.",
    "thumbnail": "/assets/images/lesson/lesson_124_thumbnail.png",
    "videoUrl": "/videos/course_018/lesson_124.mp4",
    "duration": "28:55",
    "order": 5,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_018",
    "lessonCode": "lesson_125",
    "lessonNumber": 6,
    "title": "Prepare and preprocess data for training",
    "description": "Hands-on lesson covering: prepare and preprocess data for training.",
    "thumbnail": "/assets/images/lesson/lesson_125_thumbnail.png",
    "videoUrl": "/videos/course_018/lesson_125.mp4",
    "duration": "25:53",
    "order": 6,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_018",
    "lessonCode": "lesson_126",
    "lessonNumber": 7,
    "title": "Avoid common pitfalls like overfitting",
    "description": "Hands-on lesson covering: avoid common pitfalls like overfitting.",
    "thumbnail": "/assets/images/lesson/lesson_126_thumbnail.png",
    "videoUrl": "/videos/course_018/lesson_126.mp4",
    "duration": "20:03",
    "order": 7,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_019",
    "lessonCode": "lesson_127",
    "lessonNumber": 1,
    "title": "Welcome to Python Fundamentals",
    "description": "Course introduction, roadmap, and what you'll build by the end of \"Python Fundamentals\".",
    "thumbnail": "/assets/images/lesson/lesson_127_thumbnail.png",
    "videoUrl": "/videos/course_019/lesson_127.mp4",
    "duration": "05:44",
    "order": 1,
    "isPreview": true,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_019",
    "lessonCode": "lesson_128",
    "lessonNumber": 2,
    "title": "Setting Up Your Python Environment",
    "description": "Install the required tools and set up your development environment for this course.",
    "thumbnail": "/assets/images/lesson/lesson_128_thumbnail.png",
    "videoUrl": "/videos/course_019/lesson_128.mp4",
    "duration": "15:06",
    "order": 2,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_019",
    "lessonCode": "lesson_129",
    "lessonNumber": 3,
    "title": "Understand Python syntax and core data types",
    "description": "Hands-on lesson covering: understand Python syntax and core data types.",
    "thumbnail": "/assets/images/lesson/lesson_129_thumbnail.png",
    "videoUrl": "/videos/course_019/lesson_129.mp4",
    "duration": "19:18",
    "order": 3,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_019",
    "lessonCode": "lesson_130",
    "lessonNumber": 4,
    "title": "Work with lists, dictionaries, and functions",
    "description": "Hands-on lesson covering: work with lists, dictionaries, and functions.",
    "thumbnail": "/assets/images/lesson/lesson_130_thumbnail.png",
    "videoUrl": "/videos/course_019/lesson_130.mp4",
    "duration": "16:20",
    "order": 4,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_019",
    "lessonCode": "lesson_131",
    "lessonNumber": 5,
    "title": "Apply object-oriented programming concepts in Python",
    "description": "Hands-on lesson covering: apply object-oriented programming concepts in Python.",
    "thumbnail": "/assets/images/lesson/lesson_131_thumbnail.png",
    "videoUrl": "/videos/course_019/lesson_131.mp4",
    "duration": "17:17",
    "order": 5,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_019",
    "lessonCode": "lesson_132",
    "lessonNumber": 6,
    "title": "Handle files and exceptions in Python",
    "description": "Hands-on lesson covering: handle files and exceptions in Python.",
    "thumbnail": "/assets/images/lesson/lesson_132_thumbnail.png",
    "videoUrl": "/videos/course_019/lesson_132.mp4",
    "duration": "28:31",
    "order": 6,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_019",
    "lessonCode": "lesson_133",
    "lessonNumber": 7,
    "title": "Write clean, idiomatic Python code",
    "description": "Hands-on lesson covering: write clean, idiomatic Python code.",
    "thumbnail": "/assets/images/lesson/lesson_133_thumbnail.png",
    "videoUrl": "/videos/course_019/lesson_133.mp4",
    "duration": "17:29",
    "order": 7,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_020",
    "lessonCode": "lesson_134",
    "lessonNumber": 1,
    "title": "Welcome to Clean Architecture",
    "description": "Course introduction, roadmap, and what you'll build by the end of \"Clean Architecture\".",
    "thumbnail": "/assets/images/lesson/lesson_134_thumbnail.png",
    "videoUrl": "/videos/course_020/lesson_134.mp4",
    "duration": "05:21",
    "order": 1,
    "isPreview": true,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_020",
    "lessonCode": "lesson_135",
    "lessonNumber": 2,
    "title": "Setting Up Your Clean Architecture Environment",
    "description": "Install the required tools and set up your development environment for this course.",
    "thumbnail": "/assets/images/lesson/lesson_135_thumbnail.png",
    "videoUrl": "/videos/course_020/lesson_135.mp4",
    "duration": "15:58",
    "order": 2,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_020",
    "lessonCode": "lesson_136",
    "lessonNumber": 3,
    "title": "Understand the core layers of Clean Architecture",
    "description": "Hands-on lesson covering: understand the core layers of Clean Architecture.",
    "thumbnail": "/assets/images/lesson/lesson_136_thumbnail.png",
    "videoUrl": "/videos/course_020/lesson_136.mp4",
    "duration": "26:56",
    "order": 3,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_020",
    "lessonCode": "lesson_137",
    "lessonNumber": 4,
    "title": "Separate business logic from frameworks and UI",
    "description": "Hands-on lesson covering: separate business logic from frameworks and UI.",
    "thumbnail": "/assets/images/lesson/lesson_137_thumbnail.png",
    "videoUrl": "/videos/course_020/lesson_137.mp4",
    "duration": "25:14",
    "order": 4,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_020",
    "lessonCode": "lesson_138",
    "lessonNumber": 5,
    "title": "Apply dependency inversion effectively",
    "description": "Hands-on lesson covering: apply dependency inversion effectively.",
    "thumbnail": "/assets/images/lesson/lesson_138_thumbnail.png",
    "videoUrl": "/videos/course_020/lesson_138.mp4",
    "duration": "26:52",
    "order": 5,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_020",
    "lessonCode": "lesson_139",
    "lessonNumber": 6,
    "title": "Design testable, decoupled system components",
    "description": "Hands-on lesson covering: design testable, decoupled system components.",
    "thumbnail": "/assets/images/lesson/lesson_139_thumbnail.png",
    "videoUrl": "/videos/course_020/lesson_139.mp4",
    "duration": "20:56",
    "order": 6,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_020",
    "lessonCode": "lesson_140",
    "lessonNumber": 7,
    "title": "Refactor an existing codebase toward Clean Architecture",
    "description": "Hands-on lesson covering: refactor an existing codebase toward Clean Architecture.",
    "thumbnail": "/assets/images/lesson/lesson_140_thumbnail.png",
    "videoUrl": "/videos/course_020/lesson_140.mp4",
    "duration": "21:02",
    "order": 7,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_021",
    "lessonCode": "lesson_141",
    "lessonNumber": 1,
    "title": "Welcome to GraphQL Essentials",
    "description": "Course introduction, roadmap, and what you'll build by the end of \"GraphQL Essentials\".",
    "thumbnail": "/assets/images/lesson/lesson_141_thumbnail.png",
    "videoUrl": "/videos/course_021/lesson_141.mp4",
    "duration": "09:29",
    "order": 1,
    "isPreview": true,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_021",
    "lessonCode": "lesson_142",
    "lessonNumber": 2,
    "title": "Setting Up Your Node.js Environment",
    "description": "Install the required tools and set up your development environment for this course.",
    "thumbnail": "/assets/images/lesson/lesson_142_thumbnail.png",
    "videoUrl": "/videos/course_021/lesson_142.mp4",
    "duration": "13:49",
    "order": 2,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_021",
    "lessonCode": "lesson_143",
    "lessonNumber": 3,
    "title": "Understand GraphQL's schema and type system",
    "description": "Hands-on lesson covering: understand GraphQL's schema and type system.",
    "thumbnail": "/assets/images/lesson/lesson_143_thumbnail.png",
    "videoUrl": "/videos/course_021/lesson_143.mp4",
    "duration": "24:42",
    "order": 3,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_021",
    "lessonCode": "lesson_144",
    "lessonNumber": 4,
    "title": "Write queries, mutations, and resolvers",
    "description": "Hands-on lesson covering: write queries, mutations, and resolvers.",
    "thumbnail": "/assets/images/lesson/lesson_144_thumbnail.png",
    "videoUrl": "/videos/course_021/lesson_144.mp4",
    "duration": "20:03",
    "order": 4,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_021",
    "lessonCode": "lesson_145",
    "lessonNumber": 5,
    "title": "Handle errors and validation in GraphQL",
    "description": "Hands-on lesson covering: handle errors and validation in GraphQL.",
    "thumbnail": "/assets/images/lesson/lesson_145_thumbnail.png",
    "videoUrl": "/videos/course_021/lesson_145.mp4",
    "duration": "17:35",
    "order": 5,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_021",
    "lessonCode": "lesson_146",
    "lessonNumber": 6,
    "title": "Optimize queries to avoid over-fetching",
    "description": "Hands-on lesson covering: optimize queries to avoid over-fetching.",
    "thumbnail": "/assets/images/lesson/lesson_146_thumbnail.png",
    "videoUrl": "/videos/course_021/lesson_146.mp4",
    "duration": "27:31",
    "order": 6,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_021",
    "lessonCode": "lesson_147",
    "lessonNumber": 7,
    "title": "Integrate a GraphQL API with a frontend app",
    "description": "Hands-on lesson covering: integrate a GraphQL API with a frontend app.",
    "thumbnail": "/assets/images/lesson/lesson_147_thumbnail.png",
    "videoUrl": "/videos/course_021/lesson_147.mp4",
    "duration": "22:51",
    "order": 7,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_022",
    "lessonCode": "lesson_148",
    "lessonNumber": 1,
    "title": "Welcome to Next.js in Production",
    "description": "Course introduction, roadmap, and what you'll build by the end of \"Next.js in Production\".",
    "thumbnail": "/assets/images/lesson/lesson_148_thumbnail.png",
    "videoUrl": "/videos/course_022/lesson_148.mp4",
    "duration": "05:54",
    "order": 1,
    "isPreview": true,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_022",
    "lessonCode": "lesson_149",
    "lessonNumber": 2,
    "title": "Setting Up Your React Environment",
    "description": "Install the required tools and set up your development environment for this course.",
    "thumbnail": "/assets/images/lesson/lesson_149_thumbnail.png",
    "videoUrl": "/videos/course_022/lesson_149.mp4",
    "duration": "13:48",
    "order": 2,
    "isPreview": true,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_022",
    "lessonCode": "lesson_150",
    "lessonNumber": 3,
    "title": "Build pages and layouts using the Next.js App Router",
    "description": "Hands-on lesson covering: build pages and layouts using the Next.js App Router.",
    "thumbnail": "/assets/images/lesson/lesson_150_thumbnail.png",
    "videoUrl": "/videos/course_022/lesson_150.mp4",
    "duration": "28:07",
    "order": 3,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_022",
    "lessonCode": "lesson_151",
    "lessonNumber": 4,
    "title": "Implement server-side rendering and static generation",
    "description": "Hands-on lesson covering: implement server-side rendering and static generation.",
    "thumbnail": "/assets/images/lesson/lesson_151_thumbnail.png",
    "videoUrl": "/videos/course_022/lesson_151.mp4",
    "duration": "27:25",
    "order": 4,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_022",
    "lessonCode": "lesson_152",
    "lessonNumber": 5,
    "title": "Create API routes within a Next.js app",
    "description": "Hands-on lesson covering: create API routes within a Next.js app.",
    "thumbnail": "/assets/images/lesson/lesson_152_thumbnail.png",
    "videoUrl": "/videos/course_022/lesson_152.mp4",
    "duration": "25:31",
    "order": 5,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_022",
    "lessonCode": "lesson_153",
    "lessonNumber": 6,
    "title": "Optimize images, fonts, and performance",
    "description": "Hands-on lesson covering: optimize images, fonts, and performance.",
    "thumbnail": "/assets/images/lesson/lesson_153_thumbnail.png",
    "videoUrl": "/videos/course_022/lesson_153.mp4",
    "duration": "27:06",
    "order": 6,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_022",
    "lessonCode": "lesson_154",
    "lessonNumber": 7,
    "title": "Deploy a Next.js application to production",
    "description": "Hands-on lesson covering: deploy a Next.js application to production.",
    "thumbnail": "/assets/images/lesson/lesson_154_thumbnail.png",
    "videoUrl": "/videos/course_022/lesson_154.mp4",
    "duration": "22:55",
    "order": 7,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_023",
    "lessonCode": "lesson_155",
    "lessonNumber": 1,
    "title": "Welcome to AWS for Beginners",
    "description": "Course introduction, roadmap, and what you'll build by the end of \"AWS for Beginners\".",
    "thumbnail": "/assets/images/lesson/lesson_155_thumbnail.png",
    "videoUrl": "/videos/course_023/lesson_155.mp4",
    "duration": "06:04",
    "order": 1,
    "isPreview": true,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_023",
    "lessonCode": "lesson_156",
    "lessonNumber": 2,
    "title": "Setting Up Your AWS Environment",
    "description": "Install the required tools and set up your development environment for this course.",
    "thumbnail": "/assets/images/lesson/lesson_156_thumbnail.png",
    "videoUrl": "/videos/course_023/lesson_156.mp4",
    "duration": "17:21",
    "order": 2,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_023",
    "lessonCode": "lesson_157",
    "lessonNumber": 3,
    "title": "Understand core AWS services and their use cases",
    "description": "Hands-on lesson covering: understand core AWS services and their use cases.",
    "thumbnail": "/assets/images/lesson/lesson_157_thumbnail.png",
    "videoUrl": "/videos/course_023/lesson_157.mp4",
    "duration": "25:28",
    "order": 3,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_023",
    "lessonCode": "lesson_158",
    "lessonNumber": 4,
    "title": "Launch and manage EC2 instances",
    "description": "Hands-on lesson covering: launch and manage EC2 instances.",
    "thumbnail": "/assets/images/lesson/lesson_158_thumbnail.png",
    "videoUrl": "/videos/course_023/lesson_158.mp4",
    "duration": "20:04",
    "order": 4,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_023",
    "lessonCode": "lesson_159",
    "lessonNumber": 5,
    "title": "Store and serve files using S3",
    "description": "Hands-on lesson covering: store and serve files using S3.",
    "thumbnail": "/assets/images/lesson/lesson_159_thumbnail.png",
    "videoUrl": "/videos/course_023/lesson_159.mp4",
    "duration": "16:12",
    "order": 5,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_023",
    "lessonCode": "lesson_160",
    "lessonNumber": 6,
    "title": "Manage access and permissions with IAM",
    "description": "Hands-on lesson covering: manage access and permissions with IAM.",
    "thumbnail": "/assets/images/lesson/lesson_160_thumbnail.png",
    "videoUrl": "/videos/course_023/lesson_160.mp4",
    "duration": "26:18",
    "order": 6,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_023",
    "lessonCode": "lesson_161",
    "lessonNumber": 7,
    "title": "Deploy a simple application to AWS",
    "description": "Hands-on lesson covering: deploy a simple application to AWS.",
    "thumbnail": "/assets/images/lesson/lesson_161_thumbnail.png",
    "videoUrl": "/videos/course_023/lesson_161.mp4",
    "duration": "22:17",
    "order": 7,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_024",
    "lessonCode": "lesson_162",
    "lessonNumber": 1,
    "title": "Welcome to CI/CD with GitHub Actions",
    "description": "Course introduction, roadmap, and what you'll build by the end of \"CI/CD with GitHub Actions\".",
    "thumbnail": "/assets/images/lesson/lesson_162_thumbnail.png",
    "videoUrl": "/videos/course_024/lesson_162.mp4",
    "duration": "06:16",
    "order": 1,
    "isPreview": true,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_024",
    "lessonCode": "lesson_163",
    "lessonNumber": 2,
    "title": "Setting Up Your Docker Environment",
    "description": "Install the required tools and set up your development environment for this course.",
    "thumbnail": "/assets/images/lesson/lesson_163_thumbnail.png",
    "videoUrl": "/videos/course_024/lesson_163.mp4",
    "duration": "11:07",
    "order": 2,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_024",
    "lessonCode": "lesson_164",
    "lessonNumber": 3,
    "title": "Understand core CI/CD concepts and workflows",
    "description": "Hands-on lesson covering: understand core CI/CD concepts and workflows.",
    "thumbnail": "/assets/images/lesson/lesson_164_thumbnail.png",
    "videoUrl": "/videos/course_024/lesson_164.mp4",
    "duration": "16:08",
    "order": 3,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_024",
    "lessonCode": "lesson_165",
    "lessonNumber": 4,
    "title": "Write GitHub Actions workflow files",
    "description": "Hands-on lesson covering: write GitHub Actions workflow files.",
    "thumbnail": "/assets/images/lesson/lesson_165_thumbnail.png",
    "videoUrl": "/videos/course_024/lesson_165.mp4",
    "duration": "25:09",
    "order": 4,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_024",
    "lessonCode": "lesson_166",
    "lessonNumber": 5,
    "title": "Automate testing on every pull request",
    "description": "Hands-on lesson covering: automate testing on every pull request.",
    "thumbnail": "/assets/images/lesson/lesson_166_thumbnail.png",
    "videoUrl": "/videos/course_024/lesson_166.mp4",
    "duration": "17:53",
    "order": 5,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_024",
    "lessonCode": "lesson_167",
    "lessonNumber": 6,
    "title": "Build automated deployment pipelines",
    "description": "Hands-on lesson covering: build automated deployment pipelines.",
    "thumbnail": "/assets/images/lesson/lesson_167_thumbnail.png",
    "videoUrl": "/videos/course_024/lesson_167.mp4",
    "duration": "22:52",
    "order": 6,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_024",
    "lessonCode": "lesson_168",
    "lessonNumber": 7,
    "title": "Manage secrets and environments safely",
    "description": "Hands-on lesson covering: manage secrets and environments safely.",
    "thumbnail": "/assets/images/lesson/lesson_168_thumbnail.png",
    "videoUrl": "/videos/course_024/lesson_168.mp4",
    "duration": "26:27",
    "order": 7,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_025",
    "lessonCode": "lesson_169",
    "lessonNumber": 1,
    "title": "Welcome to Testing React Native Apps",
    "description": "Course introduction, roadmap, and what you'll build by the end of \"Testing React Native Apps\".",
    "thumbnail": "/assets/images/lesson/lesson_169_thumbnail.png",
    "videoUrl": "/videos/course_025/lesson_169.mp4",
    "duration": "07:02",
    "order": 1,
    "isPreview": true,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_025",
    "lessonCode": "lesson_170",
    "lessonNumber": 2,
    "title": "Setting Up Your React Native Environment",
    "description": "Install the required tools and set up your development environment for this course.",
    "thumbnail": "/assets/images/lesson/lesson_170_thumbnail.png",
    "videoUrl": "/videos/course_025/lesson_170.mp4",
    "duration": "12:29",
    "order": 2,
    "isPreview": true,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_025",
    "lessonCode": "lesson_171",
    "lessonNumber": 3,
    "title": "Write unit tests for React Native logic with Jest",
    "description": "Hands-on lesson covering: write unit tests for React Native logic with Jest.",
    "thumbnail": "/assets/images/lesson/lesson_171_thumbnail.png",
    "videoUrl": "/videos/course_025/lesson_171.mp4",
    "duration": "28:59",
    "order": 3,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_025",
    "lessonCode": "lesson_172",
    "lessonNumber": 4,
    "title": "Test components using React Native Testing Library",
    "description": "Hands-on lesson covering: test components using React Native Testing Library.",
    "thumbnail": "/assets/images/lesson/lesson_172_thumbnail.png",
    "videoUrl": "/videos/course_025/lesson_172.mp4",
    "duration": "17:39",
    "order": 4,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_025",
    "lessonCode": "lesson_173",
    "lessonNumber": 5,
    "title": "Mock native modules and API calls in tests",
    "description": "Hands-on lesson covering: mock native modules and API calls in tests.",
    "thumbnail": "/assets/images/lesson/lesson_173_thumbnail.png",
    "videoUrl": "/videos/course_025/lesson_173.mp4",
    "duration": "24:58",
    "order": 5,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_025",
    "lessonCode": "lesson_174",
    "lessonNumber": 6,
    "title": "Set up end-to-end tests for mobile flows",
    "description": "Hands-on lesson covering: set up end-to-end tests for mobile flows.",
    "thumbnail": "/assets/images/lesson/lesson_174_thumbnail.png",
    "videoUrl": "/videos/course_025/lesson_174.mp4",
    "duration": "23:58",
    "order": 6,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  },
  {
    "courseCode": "course_025",
    "lessonCode": "lesson_175",
    "lessonNumber": 7,
    "title": "Integrate testing into a CI pipeline",
    "description": "Hands-on lesson covering: integrate testing into a CI pipeline.",
    "thumbnail": "/assets/images/lesson/lesson_175_thumbnail.png",
    "videoUrl": "/videos/course_025/lesson_175.mp4",
    "duration": "28:44",
    "order": 7,
    "isPreview": false,
    "transcriptAvailable": true,
    "notesAvailable": true,
    "isCompleted": false
  }
];

module.exports = lessons;